### ISSUE TITLE
Doesn't work with 1.18.2

### ISSUE THREAD

**Issue by ghost** [rutrum/replant-swamp-trees#2]
Doesn't working on the new version of minecraft

Here is log:

[2022-05-08-1.log.gz](https://github.com/rutrum/replant-swamp-trees/files/8647710/2022-05-08-1.log.gz)

**Comment by rutrum** [comment]
Thanks for showing care about the project.  I know we are deep into 1.19 now but it felt right to hit 1.18.2 on the way.  I just released a working version for 1.18.2.  https://github.com/rutrum/replant-swamp-trees/releases/tag/mc1.18.2-v0.0.2
